spring.application.name=HotelM
spring.datasource.url=jdbc:mysql://localhost:3306/HOTELM_DB
spring.datasource.username=root
spring.datasource.password=S@18112006ng

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true